### ISSUE TITLE
Не нужно использовать имена типа service2, у вас блок ограничивает видимость, используйте service

### ISSUE THREAD

**Issue by coursar** [Artyom16RUS/taxi-order#2]
https://github.com/Artyom16RUS/taxi-order/blob/134cf73edb02d5c90d0e8d797a3ffe9b080e3dad/src/test/java/TaxiOrderServiceTest.java#L17-L18

**Comment by Artyom16RUS** [comment]
А когда тестов станет много штук 15, их будет сложно отличать друг от друга, потому я решил им присваивать разные имена типов. Как тут быть?

**Comment by coursar** [comment]
1. Использовать блоки
2. Использовать разные тесты
